### PR TITLE
Protocol Account

### PR DESCRIPTION
**Pull request by chronaeon**
Will there ever be any more protocol accounts besides the initial crowdsale ones? Technically they can exist, but should we ever expect that to happen? It doesn't seem in line with Ethereum's main philosophy.

### CODE REVIEW

**Comment by webthethird** [comment]
I'm not sure about using the ordinal 'first', 'second' and 'third' in the definition of the types of accounts. It seems like it could potentially problematic, such as if we add new account types later on, or if one were describing the initial state of the Ethereum blockchain at launch, where one might argue that the protocol accounts (ie. from the crowdsale) came first. The order you've used for the account types makes sense to me intuitively, but to be honest it is a bit arbitrary.

**Comment by chronaeon** [comment]
I'm fine with that if you want to change it to a non-ordinal number sequence or listing.

**Comment by chronaeon** [comment]
@webthethird what are your ideas for changing it?

**Comment by jo-tud** [comment]
superseeded by #138

**Pull request closed without merging**
