### PR TITLE
better forks modeling

### PR DESCRIPTION
**Pull request by sunnya97**
Major changes

- Blocks conform to Ethereum Protocol Variants
- Added Object Property that a Blockchain contains a Block
- Added Object Property that a Blockchain has a most recent Block
- Changed "has Fork" to relate Ethereum Protocol Variants rather than Blockchains
- Got rid of Start Block Number data property

### CODE REVIEW

**Comment by jo-tud** [comment]
@sunnya97 To make it easier for me to review this PR, can you please give a short summary of the rationales for the changes?

**Comment by webthethird** [comment]
@sunnya97 Have you seen the comment from @jo-tud above?

**Comment by sunnya97** [comment]
Essentially the overall rationale for this design is to be better modeling of forks, both long term (such as Ethereum and Ethereum Classic) as well as during an ongoing short-term fork.

The reason a Block rather than a Blockchain should conform to a Protocol Variant is that different blocks within a canonical blockchain can conform to different protocols (due to a forked protocol upgrade).  Early blocks in the chain should still say that they conform the old protocol.

The Blockchain contains Block and Blockchain has most recent Block I think are pretty intuitive relationship to have.

Changed "has fork" to show when a Protocol Variant forks from another.  Forks in blockchain can be detected by the Block's conforms to Protocol Variants:
    * You can tell a soft fork when a series of blocks conforms to multiple Protocol variant
    * You can tell a hard fork when a block has a different protocol variant than its parent

**Comment by webthethird** [comment]
Thank you for the clarification @sunnya97 

This makes sense to me, since multiple blockchains resulting from a fork will contain the same canonical blocks prior to the fork, and the blockchain does not cease to contain said blocks once a new protocol variant is accepted. In that sense I agree that `Start Block Number` is unnecessary.

Also, as you mentioned in a previous conversation, the object property `hasMostRecentBlock` is useful as it makes defining the rest of the blockchain trivial by simply following the chain of parent blocks.

**Comment by jo-tud** [comment]
Most of this makes a lot of sense and is reasonable.
I have one concern though. Since a Blockchain now always starts with a genesis block, it needs relations to all blocks belonging to it. When a fork is created that would mean that all these relations would need to be duplicated. Also it is subject of politics which chain would be the "Ethereum" blockchain. The one propagated by the Ethereum foundation? Or another one?

Splitting a Blockchain up into block sequences between forks, as is the current model, avoids all these and related problems.

This needs some more work. However, in order to move forward I suggest to merge this into a separate branch of EthOn, called `BlockchainModelOverhaul` @webthethird

**Pull request merged**
