### PR TITLE
message changes

### PR DESCRIPTION
**Pull request by sunnya97**
Created 4 types of messages

- Call Messages
- Create Messages
- Transactions
- Contract Messages

instead of Call and Create Messages being subtypes of Contract Messages and Transactions.

Also, not rid of Value messages.  Addresses #72

### CODE REVIEW

**Comment by jo-tud** [comment]
This really is a major change to the Message model of EthOn. Love it.
Because of it's magnitude, please merge it to the dev branch first. I'd like to release it a bit later.
@sunnya97 What about self destruct messages? As I understand, they remain a subclass of contract message because they don't apply to Tx. Do you have the same view on that?

**Comment by jo-tud** [comment]
@webthethird Please make sure the illustrations reflect this major change.

**Comment by sunnya97** [comment]
Agreed, self destruct messages should be a subclass of Contract messages.

**Comment by webthethird** [comment]
@sunnya97 Would you mind creating a new pull request to merge this into the dev branch instead of master?

**Comment by webthethird** [comment]
@jo-tud Do you still want me to merge this into the dev branch first? Thanks for the tip on changing the base branch btw. I'm learning something new everyday!

**Pull request merged**
