### PR TITLE
removed functionality of txReciepts

### PR DESCRIPTION
**Pull request by sunnya97**
Addresses #75

### CODE REVIEW

**Comment by jo-tud** [comment]
I love this - however, it moves EthOn a big step away from the protocol specification. Therefore, please merge into dev ( @webthethird ).

@webthethird Please make sure the illustrations reflect this major change.

Here's the full rationale for the record:
Transaction Receipts are used by Ethereum nodes to persist information that can only be known after processing a transaction. In EthOn we just attach this additional information to the Tx itself, once it is known. There is no need to make the model more complex by adding Receipts because EthOn is not a specification for client implementation (unlike the YP).

**Comment by webthethird** [comment]
@jo-tud My apologies, I merged into master instead of the dev branch. Should I revert this and continue on the dev branch?

**Comment by webthethird** [comment]
@jo-tud The main illustration didn't include TxReceipts originally, so there is nothing to remove there. I am going to go over the other illustrations and update them according to the new changes.

**Comment by jo-tud** [comment]
Yes, please.

**Pull request merged**
