### PR TITLE
Account

### PR DESCRIPTION
**Pull request by chronaeon**
See commit notes for comments.

### CODE REVIEW

**Comment by chronaeon** [comment]
@jo-tud what if I put "Accounts are identified by either:

1. A public and private keypair, if it's an external and protocol account, or
2. A concatenation of the creator Account's address and its nonce, if it's a contract account."

**Comment by jo-tud** [comment]
This would be more correct (based on your start):
"Accounts are identified by and address derived from:

The public key of a public and private keypair, if it's an external and protocol account, or
A concatenation of the creator Account's address and its nonce, if it's a contract account."

**Comment by chronaeon** [comment]
It is good to have "Public key "of" a public and private keypair." rather than "Public and private keypair." +1

Would it be safe to say that addresses are always derived from the state of the chain?

**Comment by chronaeon** [comment]
"Accounts are identified by an address derived from:

The public key of a public and private keypair, if it's an external and protocol account, or
A concatenation of the creator Account's address and its nonce, if it's a contract account."

**Comment by jo-tud** [comment]
@chronaeon The state is only involved for addresses of Contract Accounts (because the nonce is part of the state)

**Comment by webthethird** [comment]
From this discussion it sounds like it would be more appropriate to discuss the derivation of addresses in the definitions of the subclasses ExternalAccount and ContractAccount. For the broader Account concept, it seems sufficient to say that 'Accounts are identified by their address.' However if you both agree to describing the two cases here, I have no objection to that.

@jo-tud Should high level concepts such as Account, EthOn Concept, etc each have a simpleDefinition in addition to the rdfs:comment? If so, it would make more sense to me to include how addresses are derived in the full definition, and write a very concise version as well for those who just want to know what the heck an Ethereum 'account' is and don't care about the subtle distinctions between addressing schemes ;)

**Comment by webthethird** [comment]
Is there any reason for eliminating the remainder of the definition? Perhaps it would be preferable to keep this part: `All accounts are associated with an Account State, and Contract Accounts may have an associated Storage State and EVM code.`

**Comment by chronaeon** [comment]
@webthethird I agree, we should keep your original contribution to the first pull request which was closed when I did the pull request genocide. `All accounts are associated with an Account State, and Contract Accounts may have an associated Storage State and EVM code.`

**Comment by webthethird** [comment]
If you don't mind @chronaeon I'd like to reformat this definition in order to incorporate the above sentence and make it read more like a short paragraph than a list. I am also going to add a simpleDefinition.

**Comment by webthethird** [comment]
Closing this as it has been moved to #133

**Pull request closed without merging**
