### PR TITLE
EthOnConcept

### PR DESCRIPTION
**Pull request by chronaeon**

### CODE REVIEW

**Comment by webthethird** [comment]
I like this as a full-length description, as it does a good job of framing the entire ontology from a philosophical point of view and its practical implications. 

For a simple version, perhaps something along the lines of:
`<ethon:simple xml:lang="en">Groups all concepts and relationships between concepts in the Ethereum space, which collectively make up the EthOn ontological framework.</ethon:simple>`

**Comment by webthethird** [comment]
On a separate note, I noticed that this PR also contains the changes committed to #98, and each subsequent PR contains all previous changes. To make these PRs truly granular, do we need to remove the unrelated changes from each branch? @jo-tud

**Comment by chronaeon** [comment]
Hmm...that's a good question. Removing other changes to make it granular is probably a best practice for future PRs etc. I will do that from now on to make sure each branch lives unto itself. 

For now maybe we can leave the remaining PRs up and once discussion is finished on each we can close the PR and submit the new one that is granular. That way we don't delete all our conversations before they are finished.

**Comment by chronaeon** [comment]
OK I've narrowed it down to three commits. If we can agree on all of these, Bill would you mind helping me change my commits in person to fix the branches? I think I could do it alone, but I could use your help to make sure I don't cause another issue when changing the commits! :D

**Pull request closed without merging**
