### PR TITLE
uncle changes

### PR DESCRIPTION
**Pull request by sunnya97**
- Remove Uncle class and made it an Object property relating a Block to a Block
- Added UncleBeneficiary and MinerBeneficiary

### CODE REVIEW

**Comment by webthethird** [comment]
Are you sure that Uncle shouldn't be kept as a subclass of Block? Would be good to have @jo-tud review this one, I'm not sure I have a strong enough opinion.

**Comment by jo-tud** [comment]
I like the sub-properties `UncleBeneficiary` and `MinerBeneficiary`. I'd suggest to change `MinerBenficiary` to `AuthorBeneficiary` because that term works better if the proofing algorithm moves away from proof of work.

I don't really understand, yet what the rationale is for removing the Uncle class all together. Please elaborate a bit, @sunnya97 .

Why is `claimsUncle` better than `knowsOfUncle`? Imo, an improvement would be `includesUncle` because the list of accepted uncles is part of the Block header. What do you think?

**Comment by sunnya97** [comment]
When Ethereum switches away from Proof of Work to Proof of Stake, the entire section of the ontology will have to be redesigned.  Casper style of PoS doesn't have a single block miner.  It also, doesn't have Uncles either.

And the reason for getting rid of Uncle was the it provides better modeling of a fork.  For example, if the blockchain temporarily forked into chain A and chain B, a block in chain A could claim one in B as an uncle, but at the same time a block in B could claim one in A as an uncle.  It's a matter of which chain's perspective you take.

And yeah, I think includesUncle might be a better name.

Thoughts?

**Comment by webthethird** [comment]
I see, so in the case of the two forks A and B, it is possible that block A(n) `includesUncle` B(n+1) and block B(n) `includesUncle` A(n+1), in which case block A(n+1) would fit the class:Uncle from the perspective of fork B but not of fork A, and visa versa. Am I correct in my understanding? If so, it makes sense to me to eliminate the Uncle class and replace it with the object property `includesUncle`

**Comment by sunnya97** [comment]
@webthethird Yep, exactly!

**Comment by jo-tud** [comment]
I agree with everything in the above discussion except for one thing. I think the uncle class is still needed. even if a block is an uncle or not, from two different perspectives, it still is an uncle. Any block that has the `includesUncle` relation pointed to it, *is* an uncle. It doesn't matter if it also is a block from another perspective - in OWL it can easily have two types.

**Comment by jo-tud** [comment]
@webthethird please merge into **dev** branch. You don't need sunny for that - you can just click on "edit" on the top right.

**Comment by webthethird** [comment]
Closing this PR, moved to #113

**Pull request closed without merging**
