### PR TITLE
recreate the main EthOn illustration using the new icons

### PR DESCRIPTION
**Pull request by webthethird**
Pivotal story: https://www.pivotaltracker.com/story/show/144516165

Replaced icons in main EthOn_overview illustration with new icons
Cleaned up graph by aligning elements and text to make more legible

### CODE REVIEW

**Comment by jo-tud** [comment]
Great job, that looks really good already.
To do:
- In the call graph box change the 3rd and forth Contract Message from the left to be of type CallContractMsg and the 1st and 2nd to be value Contract Messages

I also prefer it when the arrows don't directly attach to the icons (if there is no circular border) but have a small "gap" between the beginning of the arrow and the icon. That's not easy to accomplish though.

**Comment by webthethird** [comment]
I also would prefer if the arrows didn't touch the icons, but found it difficult to accomplish with yEd. Do you know of a trick to make this easier? It might help if each icon were contained in a shape, ie circles for accounts, squares for blocks, rectangles for blockchains, etc.

**Comment by webthethird** [comment]
@jo-tud I found a very simple way in yEd to give the arrows a gap at each end. I will push the updated version and create another pull request shortly.

**Comment by jo-tud** [comment]
cool - let me know what that way is
I also sent an email with some resources related to that problem

**Comment by webthethird** [comment]
@jo-tud I just committed the update. I don't need to create a new pull request, do I?

**Pull request merged**
